version: "3.5"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome      
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
